feat(main): SnackBar
zebrafed/zeta_flutter pull request #10
Opened 2024-03-27 07:03 UTC by sd-athlon

2024-03-27 15:57 UTC, thelukewalton approved these changes

2024-03-27 15:57 UTC, thelukewalton commented on example/widgetbook/pages/components/snack_bar_widgetbook.dart
> +        final leadingIcon = context.knobs.listOrNull<Icon>(
There is a helper function `iconKnob` that can add any custom icon, that might be good to use here

2024-03-27 15:57 UTC, thelukewalton commented on lib/src/components/snack_bar/snack_bar.dart
> +      _ => const SizedBox(),
I was wrong, there is an icon for ZetaSnackbarType.view:
`ZetaIcons.open_in_new_window_round` 
![image](https://github.com/zebrafed/zeta_flutter/assets/23633655/22f269e2-538c-4842-9fd4-0300f677311f)

2024-03-28 09:39 UTC, mikecoomber approved these changes

2024-03-29 10:32 UTC, atanasyordanov21 requested changes

2024-03-29 10:32 UTC, atanasyordanov21 commented on lib/src/components/snack_bar/snack_bar.dart
> +      ZetaSnackBarType.deletion || ZetaSnackBarType.error => colors.purple.shade10,
The color here should be `red.shade10`.

2024-03-29 11:10 UTC, atanasyordanov21 approved these changes

2024-03-29 11:10 UTC, merged