feat : Avatar update
zebrafed/zeta_flutter pull request #30
Opened 2024-04-19 12:29 UTC by ahmed-osman3

https://jira.zebra.com/browse/UX-963

2024-04-19 13:15 UTC, thelukewalton commented on example/widgetbook/pages/components/avatar_widgetbook.dart
> +      lowerBadge: context.knobs
This notification text is not aligned, and the indicator should be pill shaped: ![image](https://github.com/zebrafed/zeta_flutter/assets/23633655/837d5386-fd1f-4706-a0d3-adda118bf911)

2024-04-19 13:15 UTC, thelukewalton commented on lib/src/components/avatars/avatar.dart
> +            '$value+',
I think the '+' is only for when the value is greater than 99, otherwise it should just show the value

2024-04-19 13:15 UTC, thelukewalton commented on lib/src/components/avatars/avatar.dart
> +    this.color = Colors.red,
This should be `Zeta.of(context).colors.negative`.
You wont be able to put this in the constructor though, so just default it to null and set it further down

2024-04-19 13:15 UTC, thelukewalton commented on example/widgetbook/pages/components/avatar_widgetbook.dart
> +      lowerBadge: context.knobs.boolean(label: 'Notification Badge', initialValue: false)
can you extend this so that in widgetbook we can put custom colors and values for the badges please

2024-04-19 15:34 UTC, ahmed-osman3 commented on example/widgetbook/pages/components/avatar_widgetbook.dart
> +      lowerBadge: context.knobs
Im assuming this error arises from decimal numbers so i've limited the type of value to integers only

2024-04-22 16:09 UTC, thelukewalton commented on lib/src/components/avatars/avatar.dart
> +    return Container(
this should be pill-shaped if it is a notification:
![image](https://github.com/zebrafed/zeta_flutter/assets/23633655/1892bf49-0199-4187-8838-cd9e83877fff)
![image](https://github.com/zebrafed/zeta_flutter/assets/23633655/4ca67ddb-6e0e-4052-b836-866c75998940)

2024-04-29 13:47 UTC, thelukewalton requested changes

2024-04-29 13:47 UTC, thelukewalton commented on lib/src/components/avatars/avatar.dart
> +      height: type == ZetaAvatarBadgeType.notification ? paddedSize / 2 : paddedSize,
Height should always be consistent between notification / icon. It is the width that should change here.

2024-04-29 13:47 UTC, thelukewalton commented on lib/src/components/avatars/avatar.dart
> +          width: borderSize,
Notification type should not have a border / outline

2024-04-29 13:47 UTC, thelukewalton commented on lib/src/components/avatars/avatar.dart
> +            child: lowerBadge!.copyWith(
i think the left / right / bottom values should all be 0, not 1.

2024-04-29 13:49 UTC, ahmed-osman3 commented on lib/src/components/avatars/avatar.dart
> +      height: type == ZetaAvatarBadgeType.notification ? paddedSize / 2 : paddedSize,
I tried altering the width at first, however it seems to take up most of the space of the avatar. So to keep that 2:1 ratio of width to height, without making it have a massive impact on the avatar i opted to changing height instead

2024-04-30 09:30 UTC, thelukewalton approved these changes

2024-04-30 10:24 UTC, merged